export const USER_UPDATE_ACTION = "USER_UPDATE_ACTION";

export const LOADING_ACTION = "LOADING_ACTION";
export const LOADED_ACTION = "LOADED_ACTION";

export const USER_FETCH_FULFILLED_ACTION = "USER_FETCH_FULFILLED_ACTION";
